# Generated by Django 5.2.14 on 2026-05-18 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_alter_supplier_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='supplier_website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
