# Generated by Django 5.2.14 on 2026-07-03 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('invoice', 'Invoice'), ('proforma', 'Proforma')], default='invoice', max_length=20),
        ),
    ]
