# Generated by Django 5.2.14 on 2026-06-16 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_alter_invoiceitem_options_invoiceitem_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='quotation',
        ),
    ]
