# Generated by Django 5.2.5 on 2026-09-29 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_normalize_invoice_numbers'),
        ('quotations', '0003_quotationitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='quotation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associated_invoice', to='quotations.quotation'),
        ),
    ]
