# Generated by Django 5.2.5 on 2026-09-29 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_detach_converted_quotations'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='terms_conditions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='invoices/items/%Y/%m/'),
        ),
    ]
