# Generated by Django 5.2.14 on 2026-09-03

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("expense_number", models.CharField(blank=True, max_length=30, unique=True)),
                ("expense_date", models.DateField(default=django.utils.timezone.localdate)),
                ("category", models.CharField(choices=[("operations", "Operations"), ("transport", "Transport"), ("utilities", "Utilities"), ("salaries", "Salaries and Wages"), ("marketing", "Marketing"), ("maintenance", "Repairs and Maintenance"), ("taxes", "Taxes and Fees"), ("other", "Other")], max_length=30)),
                ("payee", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal("0.01"))])),
                ("payment_method", models.CharField(choices=[("cash", "Cash"), ("bank", "Bank Transfer / Deposit"), ("mobile", "Mobile Money"), ("cheque", "Cheque")], default="cash", max_length=20)),
                ("reference_number", models.CharField(blank=True, max_length=100)),
                ("supporting_document", models.FileField(blank=True, help_text="Upload a receipt, invoice, payment slip, or other supporting document.", null=True, upload_to="expenses/documents/%Y/%m/")),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["-expense_date", "-id"]},
        ),
    ]

