# Generated by Django 5.2.14 on 2026-07-07 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('receipt_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('kcb bank deposit', 'KCB BANK DEPOSIT'), ('nmb bank deposit', 'NMB BANK DEPOSIT'), ('kcb bank cheque', 'KCB BANK CHEQUE'), ('nmb bank cheque', 'NMB BANK CHEQUE')], default='cash', max_length=20)),
                ('payment_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='invoices.invoice')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
