# Generated by Django 5.2.14 on 2026-07-16 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='payment_reference',
        ),
        migrations.AddField(
            model_name='receipt',
            name='payment_proof',
            field=models.FileField(blank=True, help_text='Upload bank deposit slip, mobile money receipt, cheque scan or payment screenshot.', null=True, upload_to='receipts/payment_proofs/%Y/%m/', verbose_name='Payment Proof'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('tcb bank deposit', 'TCB BANK DEPOSIT'), ('nmb bank deposit', 'NMB BANK DEPOSIT'), ('tcb bank cheque', 'TCB BANK CHEQUE'), ('nmb bank cheque', 'NMB BANK CHEQUE')], default='cash', max_length=20),
        ),
    ]
