# Generated by Django 5.2.14 on 2026-07-03 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
