# Generated by Django 5.2.14 on 2026-07-03 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0002_receipt_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='title',
        ),
        migrations.AlterField(
            model_name='receipt',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('kcb bank deposit', 'KCB Bank'), ('nmb bank deposit', 'NMB Bank'), ('kcb bank cheque', 'KCB BANK Cheque'), ('nmb bank cheque', 'NMB BANK Cheque')], default='cash', max_length=20),
        ),
    ]
