# Generated by Django 5.2.14 on 2026-07-03 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0003_remove_receipt_title_alter_receipt_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('kcb bank deposit', 'KCB BANK DEPOSIT'), ('nmb bank deposit', 'NMB BANK DEPOSIT'), ('kcb bank cheque', 'KCB BANK CHEQUE'), ('nmb bank cheque', 'NMB BANK CHEQUE')], default='cash', max_length=20),
        ),
    ]
