# Generated by Django 5.2.14 on 2026-05-29 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_alter_purchase_purchase_number_purchasepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='currency',
            field=models.CharField(blank=True, choices=[('USD', 'USD'), ('TZS', 'TZS')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=12),
        ),
        migrations.AddField(
            model_name='purchase',
            name='international_shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='purchase',
            name='local_shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='purchase',
            name='purchase_category',
            field=models.CharField(blank=True, choices=[('international', 'International'), ('local', 'Local')], max_length=100, null=True),
        ),
    ]
