# Generated by Django 5.2.14 on 2026-07-15 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_alter_purchaseitem_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='purchaseproductpricing',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
