# Generated by Django 5.2.14 on 2026-05-29 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_purchase_currency_purchase_exchange_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='total_amount_tzs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
