# Generated by Django 5.2.14 on 2026-05-29 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0004_purchase_total_amount_tzs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
