# Generated by Django 5.2.14 on 2026-06-03 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
        ('purchases', '0005_alter_purchase_exchange_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseAdditionalCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_type', models.CharField(choices=[('tax', 'Import Tax'), ('clearing', 'Clearing Charges'), ('port', 'Port Charges'), ('transport', 'Local Transport'), ('insurance', 'Insurance'), ('other', 'Other')], max_length=50)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('TZS', 'TZS')], default='TZS', max_length=10)),
                ('exchange_rate', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clearing_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='costs', to='agents.clearingagent')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_costs', to='purchases.purchase')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
