# Generated by Django 5.2.14 on 2026-06-03 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0006_purchaseadditionalcost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseadditionalcost',
            name='cost_type',
            field=models.CharField(choices=[('tax', 'Import Tax'), ('clearing', 'Clearing Charges'), ('port', 'Port Charges'), ('insurance', 'Insurance'), ('other', 'Other')], max_length=50),
        ),
        migrations.CreateModel(
            name='AdditionalCostDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='additional_costs/documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('additional_cost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='purchases.purchaseadditionalcost')),
            ],
        ),
    ]
