# Generated by Django 5.2.14 on 2026-06-23 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0007_alter_purchaseadditionalcost_cost_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='international_shipping_cost',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='local_shipping_cost',
        ),
        migrations.AlterField(
            model_name='purchase',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('TZS', 'TZS')], default='TZS', max_length=10),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchase_category',
            field=models.CharField(choices=[('international', 'International'), ('local', 'Local')], default='international', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='total_amount_tzs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='purchaseadditionalcost',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='purchaseadditionalcost',
            name='cost_type',
            field=models.CharField(choices=[('shipping_international', 'International Shipping'), ('shipping_local', 'Local Transport'), ('tax', 'Import Tax'), ('clearing', 'Clearing Charges'), ('port', 'Port Charges'), ('insurance', 'Insurance'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='purchasepayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
    ]
