# Generated by Django 5.2.14 on 2026-06-24 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_productcategory_options_and_more'),
        ('purchases', '0008_remove_purchase_international_shipping_cost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseProductPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('purchase_value_tzs', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('allocated_cost_tzs', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('landed_cost_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('landed_unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchases.purchase')),
                ('purchase_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='purchases.purchaseitem')),
            ],
        ),
    ]
