# Generated by Django 5.2.14 on 2026-06-30 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quotations', '0002_paymentterms_quotation_additional_terms_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('delivery_date', models.DateField()),
                ('delivery_address', models.TextField(blank=True)),
                ('receiver_name', models.CharField(blank=True, max_length=255)),
                ('receiver_phone', models.CharField(blank=True, max_length=50)),
                ('driver_name', models.CharField(blank=True, max_length=255)),
                ('vehicle_number', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partially Delivered'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_notes', to='quotations.quotation')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryNoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('delivery_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='deliverynotes.deliverynote')),
                ('quotation_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_items', to='quotations.quotationitem')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
