# Generated by Django 5.2.14 on 2026-07-07 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deliverynotes', '0001_initial'),
        ('quotations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverynote',
            name='quotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_notes', to='quotations.quotation'),
        ),
        migrations.AddField(
            model_name='deliverynoteitem',
            name='delivery_note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='deliverynotes.deliverynote'),
        ),
        migrations.AddField(
            model_name='deliverynoteitem',
            name='quotation_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_items', to='quotations.quotationitem'),
        ),
    ]
