# Generated by Django 5.2.14 on 2026-07-15 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverynotes', '0003_alter_deliverynoteitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverynoteitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
