# Generated by Django 5.2.14 on 2026-08-14

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = [("customers", "0001_initial")]
    operations = [
        migrations.CreateModel(
            name="Lending",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("lending_date", models.DateField(default=datetime.date.today)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("returned_date", models.DateField(blank=True, null=True)),
                ("return_status", models.CharField(choices=[("active", "Active"), ("partial", "Partially returned"), ("returned", "Returned")], default="active", editable=False, max_length=20)),
                ("purpose", models.CharField(blank=True, max_length=255)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("customer", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="lendings", to="customers.customer")),
            ],
            options={"ordering": ("-lending_date", "-id")},
        ),
        migrations.CreateModel(
            name="LendingItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("item_name", models.CharField(max_length=255)),
                ("asset_tag", models.CharField(blank=True, max_length=100)),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("returned_quantity", models.PositiveIntegerField(default=0)),
                ("condition_out", models.CharField(choices=[("new", "New"), ("good", "Good"), ("fair", "Fair"), ("poor", "Poor"), ("damaged", "Damaged")], default="good", max_length=20)),
                ("condition_return", models.CharField(blank=True, choices=[("new", "New"), ("good", "Good"), ("fair", "Fair"), ("poor", "Poor"), ("damaged", "Damaged")], max_length=20)),
                ("notes", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("lending", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to="lendings.lending")),
            ],
            options={"ordering": ("id",)},
        ),
    ]
