# Generated by Django 5.2.14 on 2026-06-30 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('terms', models.TextField()),
                ('is_default', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='quotation',
            name='additional_terms',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='completion_period_from',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quotation',
            name='completion_period_to',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quotation',
            name='completion_period_unit',
            field=models.CharField(choices=[('days', 'Days'), ('weeks', 'Weeks'), ('months', 'Months')], default='days', max_length=10),
        ),
        migrations.AddField(
            model_name='quotation',
            name='payment_terms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='quotations.paymentterms'),
        ),
    ]
