# Generated by Django 5.2.14 on 2026-07-02 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0002_paymentterms_quotation_additional_terms_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=300)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['term'],
            },
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='payment_terms',
        ),
        migrations.DeleteModel(
            name='PaymentTerms',
        ),
        migrations.AddField(
            model_name='quotation',
            name='payment_terms',
            field=models.ManyToManyField(blank=True, related_name='quotations', to='quotations.paymentterm'),
        ),
    ]
