# Generated by Django 5.2.5 on 2026-09-29 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0003_quotationitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='proforma_sync_ended',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
