# Generated by Django 5.2.14 on 2026-07-06 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_is_tangible'),
        ('quotations', '0003_paymentterm_remove_quotation_payment_terms_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationitem',
            name='item_name',
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='is_tangible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotation_items', to='products.product'),
        ),
    ]
