# Generated by Django 5.2.14 on 2026-07-06 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0004_remove_quotationitem_item_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='additional_terms',
        ),
    ]
