"""Create and reconcile sales generated by fully-paid invoices."""

from decimal import Decimal

from django.db import transaction

from invoices.models import Invoice
from products.services.stock import move_stock
from sales.models import Sale, SaleItem, SalePayment


class InvoiceSaleConversionError(Exception):
    """The invoice cannot safely be represented as a stock sale."""


def _move_sale_stock(sale, direction, notes):
    """Create a stock movement for every product line on a generated sale."""
    for item in sale.items.select_related("product"):
        move_stock(
            product=item.product,
            quantity=item.quantity,
            direction=direction,
            movement_type="sale",
            reference=sale,
            notes=notes,
        )


def _validate_invoice_items(invoice):
    missing_product = [
        item.description or f"line {item.pk}"
        for item in invoice.items.all()
        if item.product_id is None
    ]
    if missing_product:
        raise InvoiceSaleConversionError(
            "This invoice has item(s) without a product: "
            f"{', '.join(missing_product)}. Add products before recording its final receipt."
        )


def _sale_payment_method(receipt_method):
    """Translate receipt payment methods to the sale payment choices."""
    method = (receipt_method or "").lower()
    if method == "cash":
        return "cash"
    if "cheque" in method:
        return "cheque"
    if "bank" in method or "deposit" in method:
        return "bank"
    return "mobile"


def _sync_sale_payments(sale, invoice):
    """Mirror all invoice receipts on its protected generated sale."""
    receipts = list(invoice.receipts.all().order_by("id"))

    # Invoice-generated sales cannot be paid from the sales workflow, so all
    # their payment rows are owned by this reconciliation service.
    sale.payments.all().delete()
    SalePayment.objects.bulk_create(
        [
            SalePayment(
                sale=sale,
                payment_date=receipt.receipt_date,
                amount=receipt.amount,
                payment_method=_sale_payment_method(receipt.payment_method),
                reference_number=receipt.receipt_number,
                notes=receipt.notes
                or f"Generated from receipt {receipt.receipt_number}.",
            )
            for receipt in receipts
        ]
    )

    amount_paid = sum(
        (receipt.amount for receipt in receipts),
        Decimal("0.00"),
    )
    sale.amount_paid = amount_paid
    sale.balance = sale.total_amount - amount_paid
    if amount_paid <= 0:
        sale.payment_status = "pending"
    elif amount_paid < sale.total_amount:
        sale.payment_status = "partial"
    else:
        sale.payment_status = "paid"


@transaction.atomic
def reconcile_invoice_sale(invoice):
    """
    Keep the generated sale in sync with an invoice payment state.

    This is intentionally invoked after every receipt create, update, and
    delete.  The one-to-one source link makes conversion idempotent, while a
    cancelled sale preserves the audit trail if a later receipt is reduced.
    """
    invoice = (
        Invoice.objects.select_for_update()
        .select_related("customer")
        .prefetch_related("items__product", "receipts")
        .get(pk=invoice.pk)
    )
    sale = (
        Sale.objects.select_for_update()
        .filter(source_invoice=invoice)
        .first()
    )

    if invoice.status != "paid":
        if sale:
            if sale.status != "cancelled":
                _move_sale_stock(
                    sale,
                    direction="in",
                    notes=f"Invoice {invoice.invoice_number} payment reversal",
                )
            _sync_sale_payments(sale, invoice)
            sale.status = "cancelled"
            sale.save(
                update_fields=[
                    "amount_paid",
                    "balance",
                    "payment_status",
                    "status",
                ]
            )
        return sale

    _validate_invoice_items(invoice)

    if sale is None:
        sale = Sale.objects.create(
            customer=invoice.customer,
            source_invoice=invoice,
            sale_date=invoice.invoice_date,
            notes=f"Automatically generated from paid invoice {invoice.invoice_number}.",
            subtotal=invoice.subtotal,
            total_amount=invoice.total_amount,
            amount_paid=Decimal("0.00"),
            balance=invoice.total_amount,
            payment_status="pending",
            status="confirmed",
        )
        for invoice_item in invoice.items.all():
            SaleItem.objects.create(
                sale=sale,
                product=invoice_item.product,
                quantity=invoice_item.quantity,
                unit_price=invoice_item.unit_price,
            )
        _move_sale_stock(
            sale,
            direction="out",
            notes=f"Generated from paid invoice {invoice.invoice_number}",
        )
        _sync_sale_payments(sale, invoice)
        sale.save(
            update_fields=["amount_paid", "balance", "payment_status"]
        )
        return sale

    # A paid invoice can become unpaid after a receipt edit/deletion and later
    # be fully paid again. Restore the same sale rather than creating another.
    if sale.status == "cancelled":
        _move_sale_stock(
            sale,
            direction="out",
            notes=f"Invoice {invoice.invoice_number} payment restored",
        )

    sale.customer = invoice.customer
    sale.sale_date = invoice.invoice_date
    sale.subtotal = invoice.subtotal
    sale.total_amount = invoice.total_amount
    _sync_sale_payments(sale, invoice)
    sale.status = "confirmed"
    sale.save(
        update_fields=[
            "customer",
            "sale_date",
            "subtotal",
            "total_amount",
            "amount_paid",
            "balance",
            "payment_status",
            "status",
        ]
    )
    return sale
