# Generated by Django 5.2.14 on 2026-06-30 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-id']},
        ),
    ]
