# Generated by Django 5.2.14 on 2026-07-06 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_sale_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesproductpricing',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Sales Product Pricing', 'verbose_name_plural': 'Sales Product Pricing'},
        ),
        migrations.AddField(
            model_name='salesproductpricing',
            name='declared_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='salesproductpricing',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14),
        ),
    ]
