# Generated by Django 5.2.14 on 2026-08-06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0004_alter_invoiceitem_quantity"),
        ("sales", "0003_alter_saleitem_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="source_invoice",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="generated_sale",
                to="invoices.invoice",
            ),
        ),
    ]
