# Generated by Django 5.2.14 on 2026-05-18 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UnitOfMeasure',
            new_name='ProductUnit',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='unit_of_measure',
            new_name='product_unit',
        ),
    ]
