# Generated by Django 5.2.14 on 2026-06-30 09:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockmovement',
            options={},
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='reference',
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='direction',
            field=models.CharField(choices=[('in', 'Stock In'), ('out', 'Stock Out')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='object_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('purchase', 'Purchase'), ('sale', 'Sale'), ('lending', 'Lending'), ('return', 'Return'), ('adjustment', 'Adjustment'), ('production', 'Production'), ('damage', 'Damage'), ('transfer', 'Transfer')], max_length=20),
        ),
    ]
