# Generated by Django 5.2.14 on 2026-07-06 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_stockmovement_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_tangible',
            field=models.BooleanField(default=True),
        ),
    ]
