# Generated by Django 5.2.14 on 2026-06-04 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_average_cost_product_current_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='markup_percentage',
            field=models.DecimalField(decimal_places=2, default=30, max_digits=5),
        ),
    ]
