# Generated by Django 5.2.14 on 2026-06-04 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_markup_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='markup_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
