# Generated by Django 5.2.14 on 2026-06-04 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_markup_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='markup_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=30.0, max_digits=5),
        ),
    ]
