# Generated by Django 5.2.14 on 2026-06-23 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_markup_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='markup_percentage',
        ),
    ]
