# Generated by Django 5.2.14 on 2026-06-23 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_product_markup_percentage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ['name'], 'verbose_name_plural': 'Product Categories'},
        ),
        migrations.AlterModelOptions(
            name='productunit',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='product',
            name='average_cost',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock_value',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='total_cost',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='unit_cost',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('stock', 'Stock Item'), ('service', 'Service'), ('consumable', 'Consumable'), ('asset', 'Asset')], default='stock', max_length=20),
        ),
    ]
